use tienda;
select distinct nombre from producto;
select distinct nombre, precio from producto;
Select * from producto;
select nombre, precio as 'precio EUR', 1.161 * precio as 'precio dolar' from producto;
select nombre as 'nom de producto', precio as 'euros', 1.161 * precio as 'dolars' from producto;
Select upper(nombre), precio from producto;
Select lower(nombre), precio from producto;
select nombre, upper(substr(nombre,1,2)) from fabricante;
select nombre, round(precio) from producto;
select nombre, truncate(precio,0) from producto;
select fabricante.codigo from fabricante inner join producto on producto.codigo_fabricante = fabricante.codigo;
select distinct fabricante.codigo from fabricante inner join producto on producto.codigo_fabricante = fabricante.codigo;
select nombre from fabricante order by nombre;
select nombre from fabricante order by nombre desc;
select nombre from producto order by nombre, precio desc;
select * from fabricante limit 5;
select * from fabricante limit 2 offset 3;
select nombre, precio from producto order by precio asc limit 1;
select nombre, precio from producto order by precio desc limit 1;
select nombre from producto where codigo_fabricante = 2;
select producto.nombre, producto.precio, fabricante.nombre as 'fabricante' from producto left join fabricante on producto.codigo_fabricante = fabricante.codigo;
select producto.nombre, producto.precio, fabricante.nombre as 'fabricante' from producto left join fabricante on producto.codigo_fabricante = fabricante.codigo order by fabricante.nombre;
select producto.nombre, producto.precio, fabricante.codigo, fabricante.nombre as 'fabricante' from producto left join fabricante on producto.codigo_fabricante = fabricante.codigo;
select p.nombre, p.precio, f.nombre from producto as p left join fabricante as f on f.codigo = p.codigo_fabricante order by precio asc limit 1;
select p.nombre, p.precio, f.nombre from producto as p left join fabricante as f on f.codigo = p.codigo_fabricante order by precio desc limit 1;
select p.* from producto as p left join fabricante as f on f.codigo = p.codigo_fabricante where f.nombre = 'Lenovo';
select p.* from producto as p left join fabricante as f on f.codigo = p.codigo_fabricante where f.nombre = 'Crucial' AND precio > 200;
select p.* from producto as p left join fabricante as f on f.codigo = p.codigo_fabricante where f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre='Seagate';
select p.* from producto as p left join fabricante as f on f.codigo = p.codigo_fabricante where f.nombre in ('Asus','Hewlett-Packard','Seagate');
select p.nombre, p.precio, f.nombre from producto p left join fabricante as f on f.codigo = p.codigo_fabricante where f.nombre LIKE '%e';
select p.nombre, p.precio, f.nombre from producto p left join fabricante as f on f.codigo = p.codigo_fabricante where f.nombre LIKE '%w%';
select p.nombre, p.precio, f.nombre from producto as p left join fabricante as f on f.codigo = p.codigo_fabricante where p.precio >= 180 order by p.precio desc, p.nombre asc;
select distinct f.codigo, f.nombre from fabricante as f inner join producto as p on p.codigo_fabricante=f.codigo;
select f.codigo, f.nombre, p.nombre from fabricante as f left join producto as p on p.codigo_fabricante=f.codigo;
select f.codigo, f.nombre from fabricante as f left join producto as p on p.codigo_fabricante=f.codigo where p.codigo is null;
select *  from producto where codigo_fabricante in (select codigo from fabricante where nombre = 'Lenovo');
select * from producto where precio = (select max(precio) as precio from producto group by codigo_fabricante having codigo_fabricante in (select codigo from fabricante where nombre = 'Lenovo'));
select nombre from producto where codigo_fabricante in (select codigo from fabricante where nombre = 'Lenovo') order by precio desc limit 1;
select nombre from producto where codigo_fabricante in (select codigo from fabricante where nombre = 'Hewlett-Packard') order by precio asc limit 1;
select * from producto where precio >= (select precio from producto where codigo_fabricante in (select codigo from fabricante where nombre = 'Lenovo') order by precio desc limit 1);
select * from producto where precio >= (select avg(precio) from producto where codigo_fabricante in (select codigo from fabricante where nombre = 'Asus') group by codigo_fabricante);
use universidad;
select apellido1, apellido2, nombre from persona where tipo ='alumno' order by apellido1, apellido2, nombre;
select nombre, apellido1, apellido2 from persona where tipo ='alumno' AND telefono is NULL;
select nombre, apellido1, apellido2 from persona where tipo = 'alumno' AND year(fecha_nacimiento) = 1999;
select nombre, apellido1, apellido2 from persona where tipo = 'profesor' AND telefono is NULL and NIF LIKE '%K';
select nombre from asignatura where cuatrimestre = 1 AND id_grado= 7 AND curso = 3;
select p.apellido1, p.apellido2, p.nombre, d.nombre as departamento from persona as p left join profesor as prof on prof.id_profesor = p.id left join departamento as d on d.id = prof.id_departamento where p.tipo = 'profesor' order by apellido1, apellido2,p.nombre;
select  a.nombre, ce.anyo_inicio, ce.anyo_fin  from alumno_se_matricula_asignatura as asma left join asignatura as a on asma.id_asignatura = a.id left join curso_escolar as ce on ce.id = asma.id_curso_escolar where id_alumno in (select id from persona where nif = '26902806M');
select distinct d.nombre as departamento from departamento as d right join profesor as p on d.id=p.id_departamento left join asignatura as a on a.id_profesor=p.id_profesor right join grado as g on a.id_grado=g.id where g.nombre = 'Grado en Ingenieria Informàtica (Plan 2015)';
select distinct p.nombre, p.apellido1, p.apellido2 from alumno_se_matricula_asignatura as asma left join persona as p on p.id = asma.id_alumno where id_curso_escolar in (select id from curso_escolar where anyo_inicio = 2018 AND anyo_fin= 2019);
select p.apellido1, p.apellido2, p.nombre, d.nombre as departamento from profesor as prof right join departamento as d on d.id=prof.id_departamento right join persona as p on p.id = prof.id_profesor where p.tipo= 'profesor' order by d.nombre, apellido1, apellido2, nombre;
select pers.nombre, pers.apellido1, pers.apellido2 from  profesor as p right join  persona as pers on pers.id=p.id_profesor where pers.tipo = 'profesor' and p.id_departamento is null;
select d.nombre as departamento from  departamento as d left join profesor as p on d.id=p.id_departamento where p.id_profesor is null;
select persona.nombre, persona.apellido1, persona.apellido2 from persona right join profesor as p on p.id_profesor = persona.id left join asignatura as a on a.id_profesor = p.id_profesor where a.id is null;
select a.nombre from profesor as p right join asignatura as a on a.id_profesor = p.id_profesor where p.id_profesor is null;
select d.nombre from profesor as p right join asignatura as a on a.id_profesor = p.id_profesor right join departamento as d on d.id = p.id_departamento where a.id is null;
select count(id) as total_alumnos from persona group by tipo having tipo = 'alumno';
 select count(id) as total_alumnos_1999 from persona where year(fecha_nacimiento) = 1999 group by tipo having tipo = 'alumno' ;
select d.nombre as departamento, count(p.id_profesor) as num_profesores from departamento as d inner join profesor as p on d.id = p.id_departamento group by d.nombre order by num_profesores desc;
select d.nombre as departamnto , count(p.id_profesor) as num_profesores from departamento as d left join profesor as p on d.id = p.id_departamento group by d.nombre; 
select g.nombre, count(a.id) as assignatures from grado as g left join asignatura as a on g.id = a.id_grado group by g.nombre order by assignatures desc;
select g.nombre, count(a.id) as assignatures from grado as g left join asignatura as a on g.id = a.id_grado group by g.nombre having assignatures>40 order by assignatures desc;
select g.nombre, a.tipo, sum(a.creditos) as total_creditos from grado as g right join asignatura as a on a.id_grado = g.id group by g.id, a.tipo;
select ce.anyo_inicio, ce.anyo_fin, count(asma.id_alumno) as num_alumnos from alumno_se_matricula_asignatura as asma left join curso_escolar as ce on ce.id = asma.id_curso_escolar group by ce.id;
select p.id, p.nombre, p.apellido1, p.apellido2, count(a.id) as assignatures_impartides from persona as p left join asignatura as a on p.id=a.id_profesor where p.tipo = 'profesor' group by p.id;
select * from persona where tipo ='alumno' order by fecha_nacimiento asc limit 1;
select pers.nombre, pers.apellido1, pers.apellido2 from profesor as p left join persona as pers on pers.id=p.id_profesor left join asignatura as a on a.id_profesor=p.id_profesor group by a.id having a.id is null;